export const apiData = {
  movies: [
    {
      title: "1917",
      description: "Os cabos Schofield e Blake são jovens soldados britânicos durante a Primeira Guerra Mundial. Quando eles são encarregados de uma missão aparentemente impossível, os dois precisam atravessar território inimigo, lutando contra o tempo, para entregar uma mensagem que pode salvar cerca de 1600 colegas de batalhão.",
      imageLogo: "https://amblin.com/wp-content/uploads/2019/07/1917_2020_logo-400x162.png",
      imagePoster: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/m6VVgmwNdOWvLo8nlheLPQU5wr7.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/lr17gkfPjS7sv8plOMrBEb9hz3P.jpg",
      linkSite: "https://www.primevideo.com/dp/amzn1.dv.gti.fe8d34b0-285f-45b4-9233-502dc60d0e1a?autoplay=0&ref_=atv_cf_strg_wb",
      linkVideo: "3gy6K7LXHg",
      category: "movies",
      favorite: false,
    },
    {
      title: "Dark",
      description: "Uma criança desaparecida coloca quatro famílias numa busca frenética por respostas enquanto desvendam um mistério alucinante que se estende por três gerações.",
      imageLogo: "https://occ-0-4907-3852.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABe6djmh4TTZ1MrGJCMa8_jmo2U43eglUCzhYKSBSVSFfovoDIl_6dxkA_SBobKb722wjW9JunuyupJtn_lmGXFYTmw_kq0pIo-m1nNPdE2QfOW_5MX9-y8kAPee7yzgXSpPOPN6XyDxoGasmvG6gbXb90r5tiaMsvvDy6gYUUY84dK7nmueqvw.png?r=50f",
      imagePoster: "https://image.tmdb.org/t/p/original/wSXJHO9WHLb0aCwvQrtco7vOmWA.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/57jxJRWWQVY3J1ZA9m09QfL1Ttt.jpg",
      linkSite: "https://www.netflix.com/br/title/80057281#:~:text=A%20pequena%20cidade%20de%20Hawkins,uma%20menina%20com%20poderes%20sobrenaturais.",
      linkVideo: "cq2iTHoLrt0",
      category: "series",
      favorite: false,
    },
   {
      title: "O Jogo da Imitação",
      description: "Em 1939, a recém-criada agência de inteligência britânica MI6 recruta Alan Turing, um aluno da Universidade de Cambridge, para entender códigos nazistas, incluindo o Enigma, que criptógrafos acreditavam ser inquebrável.",
      imageLogo: "https://occ-0-4907-3852.1.nflxso.net/dnm/api/v6/LmEnxtiAuzezXBjYXPuDgfZ4zZQ/AAAABSO1mI0bA-Pw6sTZJDDj_fbiooJJwLtzcTgp5sq5UzuPs5BdbyE86-eqCJbq_x6HQe7h5EF8C1Zf151odsu7t9TqBGt6T6Z7F3IHnrEMQ2El.png?r=d03",
      imagePoster: "https://image.tmdb.org/t/p/original/f6cRsSrOlET0Hees6jAQDYENttk.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/3YJZUjqLS424Ujy3qAJBXf5sSxO.jpg",
      linkSite: "https://www.netflix.com/br/title/70295172",
      linkVideo: "GxokSkSqF5E",
      category: "movies",
      favorite: false,
    },
    {
      title: "Breaking Bad",
      description: "Um professor do secundário com câncer do pulmão terminal junta-se a um ex-aluno para fabricar e vender metanfetamina como forma de garantir o futuro da sua família.",
      imageLogo: "https://occ-0-4907-3852.1.nflxso.net/dnm/api/v6/LmEnxtiAuzezXBjYXPuDgfZ4zZQ/AAAABeJo_eP3qXqDWnaRWhbGbLu1VN_yACCncu6G7-CW4pCSzZD74lWxcVvYw4koEFN9bmO2PERuTLR7KiXVURG1MSTFXlS9GTB0selwbgbCBtTR.png?r=295",
      imagePoster: "https://img.elo7.com.br/product/zoom/26A857B/big-poster-serie-breaking-bad-lo02-tamanho-90x60-cm-poster.jpg",
      imageBanner: "https://images.hdqwalls.com/wallpapers/breaking-bad-poster.jpg",
      linkSite: "https://www.netflix.com/br/title/70143836#:~:text=Um%20professor%20do%20secund%C3%A1rio%20com,o%20futuro%20da%20sua%20fam%C3%ADlia.&text=Veja%20tudo%20o%20que%20quiser.&text=%22Ruptura%20Total%22%20venceu%20um%20total,Ator%20Dram%C3%A1tico%2C%20para%20Bryan%20Cranston.",
      linkVideo: "FH_Pm-0kuFc",
      category: "series",
      favorite: false,
    },
    {
      title: "Hereditário",
      description: "Após a morte da reclusa avó, a família Graham começa a desvendar algumas coisas. Mesmo após a partida da matriarca, ela permanece como se fosse uma sombra sobre a família, especialmente sobre a solitária neta adolescente, Charlie.",
      imageLogo: "https://upload.wikimedia.org/wikipedia/commons/7/78/Hereditary_Logo.png",
      imagePoster: "https://image.tmdb.org/t/p/original/gre8CqQvG6D5FdhvnbS1gjmKUnB.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/8Z8njxARIoyt57agKeiCxnKWIiW.jpg",
      linkSite: "https://www.netflix.com/br-en/title/80238910",
      linkVideo: "Ui13PlmyZhQ",
      category: "movies",
      favorite: false,
    },
    {
      title: "O Senhor dos Anéis: Os Anéis de Poder",
      description: "Baseado em “O Senhor dos Anéis” de J.R.R. Tolkien, uma nova aliança de personagens icônicos é forjada para enfrentar o ressurgimento de Sauron, o Senhor Sombrio, na Terra-média.",
      imageLogo: "https://m.media-amazon.com/images/S/pv-target-images/2ca088555052e8d58e3ff60f8d29c6e7aa6961fd3b8f0d8fd4c0ef5114b54a0c._SX600_FMpng_.png",
      imagePoster: "https://http2.mlstatic.com/D_NQ_NP_619085-MLB51631310837_092022-O.webp",
      imageBanner: "https://i.redd.it/cop3wxfau7s91.png",
      linkSite: "https://www.primevideo.com/-/pt/detail/0TAPPIZDTWUZORUA92KX2Q54V2/ref=atv_dp_btf_el_prime_sd_tv_resume_t1ADAAAAAA0wg0?language=pt_BR&autoplay=1&t=2533",
      linkVideo: "rYXfmXfeM38",
      category: "series",
      favorite: true,
    },
    {
      title: "A Casa do Dragão",
      description: "Mais de 200 anos antes de “Game of Thrones”, uma guerra sangrenta entre dragões começa quando os meio-irmãos Aegon II e Rhaenyra Targaryen disputam o Trono de Ferro.",
      imageLogo: "https://hbomax-images.warnermediacdn.com/2022-10/tt_br_dsk.png?host=wme-hbomax-drupal-prod.s3.amazonaws.com",
      imagePoster: "https://scontent.fgyn24-1.fna.fbcdn.net/v/t39.30808-6/299845902_10159240664358877_6559190463137735954_n.jpg?stp=dst-jpg_s640x640&_nc_cat=106&ccb=1-7&_nc_sid=dd5e9f&_nc_ohc=0Aop7837sNUAX_MldXd&_nc_ht=scontent.fgyn24-1.fna&oh=00_AfBactZSxOoZM05CKDrXziTN1UGko2NCKtqwzbQDxBJWvA&oe=65E4F1DA",
      imageBanner: "https://images2.alphacoders.com/129/1294169.jpg",
      linkSite: "https://play.max.com/video/watch/847404c3-4390-4195-bf4b-465a8935fd04/b49e6588-9b74-4c96-b28e-28a365a3b76c",
      linkVideo: "IlGXupyQk-M",
      category: "series",
      favorite: true,
    },
    {
      title: "O Senhor dos Anéis: A Sociedade do Anel",
      description: "Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do terrível Sauron.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/10/12/b5d2d2af-0d78-334a-8b7e-65085f90bcd9.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/145TmixCmZtsMALVVssUyZJROXh.jpg",
      imageBanner: "https://images.cdn.prd.api.discomax.com/2023/09/30/72dbbf94-aea5-3da8-ac42-ead27048ab3b.jpeg?w=1700&f=webp",
      linkSite: "https://play.max.com/movie/cc028130-b24d-48b1-97ad-78cc38011625",
      linkVideo: "tDsxmvt-4Cs",
      category: "movies",
      favorite: false,
    },
    {
        title: "O Senhor dos Anéis: As Duas Torres",
        description: "Os hobbits Frodo e Sam seguem sua jornada rumo ao Monte da Perdição para destruir o anel e descobrem que estão sendo perseguidos pela misteriosa criatura Gollum.",
        imageLogo: "https://images.cdn.prd.api.discomax.com/2023/04/13/3fe471f1-8875-34e7-9e8b-041a2536baa7.png?w=600&f=webp",
        imagePoster: "https://image.tmdb.org/t/p/original/vCiyZDOIaHZJqLWrUtrE0P55qQa.jpg",
        imageBanner: "https://images.cdn.prd.api.discomax.com/2023/03/31/bdba4ea9-33d0-32cb-b264-96b231152e7d.jpeg?w=1700&f=webp",
        linkSite: "https://play.max.com/movie/91054a4b-b3cd-44d9-b6d5-564a6ec01da1",
        linkVideo: "tDsxmvt-4Cs",
        category: "movies",
        favorite: false,
      },
      {
          title: "O Senhor dos Anéis: O Retorno do Rei",
          description: "O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron envia seus exércitos em um grande ataque a Minas Tirith.",
          imageLogo: "https://images.cdn.prd.api.discomax.com/2023/04/04/1778ec56-14db-37cd-8be3-f76f42b24fc6.png?w=400&f=webp",
          imagePoster: "https://image.tmdb.org/t/p/original/dqd7JdEMX0JgXw3Hw0sBM9iRrJz.jpg",
          imageBanner: "https://image.tmdb.org/t/p/original/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
          linkSite: "https://play.max.com/movie/138a65ad-be35-4554-b57f-60d38c7ff0f0",
      linkVideo: "tDsxmvt-4Cs",
      category: "movies",
      favorite: true,
    },
    {
      title: "The Boys",
      description: "Em um mundo onde os super-heróis são tão populares que são tratados como verdadeiras celebridades, um grupo deles, chamado Os Sete, começa a abusar de seus poderes.",
      imageLogo: "https://rollingstone.uol.com.br/media/stories/quem-e-o-mais-poderoso-em-boys/assets/2.png",
      imagePoster: "https://i.ebayimg.com/images/g/LfsAAOSwgDdiuMMD/s-l1200.webp",
      imageBanner: "https://images3.alphacoders.com/124/1243773.jpg",
      linkSite: "https://www.primevideo.com/-/pt/detail/0OBCCGYKAAAAYD4D0J29QKHBWD/ref=atv_dp_btf_el_prime_sd_tv_resume_t1ADAAAAAA0wg0?autoplay=1&t=3495",
      linkVideo: "3fv0iVcCeh4",
      category: "series",
      favorite: false,
    },
    {
        title: "Game of Thrones",
        description: "Forças sobrenaturais estão despertando para devastar os Sete Reinos de Westeros, enquanto conspirações e disputas decidem quem permanecerá sentado no Trono de Ferro.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/04/26/1715240c-50cc-39e9-999f-d1b5defb4a22.png?w=600&f=webp",
      imagePoster: "https://imageio.forbes.com/specials-images/imageserve/5caf83b631358e5bca379532/Poster/960x0.jpg?height=1027&width=711&fit=bounds",
      imageBanner: "https://r4.wallpaperflare.com/wallpaper/841/564/4/daenerys-targaryen-emilia-clarke-game-of-thrones-women-fantasy-girl-hd-wallpaper-64d66229b213239003197f02b043fac8.jpg",
      linkSite: "https://play.max.com/video/watch/83eca32a-12d2-4e05-8245-e17855c9e390/9e111467-7126-440d-8b90-22072e2c19c4",
      linkVideo: "IlGXupyQk-M",
      category: "series",
      favorite: true,
    },
    {
      title: "Harry Potter e a Pedra Filosofal",
      description: "Ao completar 11 anos, Harry Potter descobre que é um bruxo e que é esperado como aluno da Escola de Magia e Bruxaria de Hogwarts.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/04/10/de08c8f6-3892-356f-8e2b-b83b2447452d.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/4rtsbE9aQ1qw4gv7yYwaNYfWFoS.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
      linkSite: "https://play.max.com/movie/742e9d46-2692-4f3f-9272-0b76d66c891f",
      linkVideo: "SFzft_2dcV0",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e a Câmara Secreta",
      description: "A Câmara Secreta foi aberta! Harry Potter e seus amigos enfrentam uma força obscura que aterroriza os corredores de Hogwarts.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/03/28/4ccbe8dc-5132-34d8-a657-9fd7dad7b720.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/811j0Jf2D0mK1U6RxXJoZgOB29n.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/yHzyPJrVqlTySQ9mc379yxrLBYQ.jpg",
      linkSite: "https://play.max.com/movie/48674b82-9076-4080-a40c-379efad5eb89",
      linkVideo: "cf0rRYvDuys",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e o Prisioneiro de Azkaban",
      description: "A vida de Harry Potter está em perigo mais uma vez quando o perigoso feiticeiro Sirius Black foge da Prisão de Azkaban para Hogwarts.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/10/12/1c86b61b-e841-3f2c-8ae4-f5b4e0929359.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/1HdMUghqlgOIvbsU9ZtO40IPRzl.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/fVgBU3KJAWHS55FPdbsZQ3YQG2Z.jpg",
      linkSite: "https://play.max.com/movie/73553a76-1658-45f6-9e26-1b9c4443b0d6",
      linkVideo: "e02fwhC6DiQ",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e o Cálice de Fogo",
      description: "Com o início das aulas, Harry sai da casa dos tios e encontra os amigos Ronny e Hermione para ver a Copa Mundial de Quadribol.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/03/28/bf8fdaff-f247-38c1-a840-ce6d655b5dc5.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/5oWB3hjzyECRBAjgWkmZinxl9qA.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/1OV7hau4D3rWGS5bu8sqBYeVpe.jpg",
      linkSite: "https://play.max.com/movie/d2e9ff29-e71d-4eae-9a4b-7cd0e00236ea",
      linkVideo: "cVKkL4O60IM",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e a Ordem da Fênix",
      description: "Vendo que ninguém acredita no retorno de Lord Voldemort, Harry decide treinar secretamente um grupo de estudantes para a iminente batalha.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/10/12/1c80a976-b623-3e29-a5c4-339b94c9b19a.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/tIf9aUyNljda9MG1pjlOLHCZ3b0.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/82a7AGF081PzFfoM8GAVGMvZNYK.jpg",
      linkSite: "https://play.max.com/movie/25768909-39b8-4cb2-a39f-e059460f7add",
      linkVideo: "ZkDCaxUNV3o",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e o Enigma do Príncipe",
      description: "Dumbledore e Harry embarcam numa série de viagens perigosas na tentativa de descobrir o segredo para destruir Lord Voldemort.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/03/28/5db58a08-5cd2-35f7-a8d7-b50b10689ed6.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/hTQQ5l9mxA3Rob8PTyvrNNGuj6y.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/iy0QpPxhmAhDjD8p7ukYHQB8HMh.jpg",
      linkSite: "https://play.max.com/movie/cba1d85a-5ef4-4ba3-b537-1d24554fe85c",
      linkVideo: "wgkHfUaG1nI",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e as Relíquias da Morte - Parte 1",
      description: "Harry foi sobrecarregado com uma tarefa sombria, perigosa e aparentemente impossível: localizar e destruir as Horcruxes restantes de Voldemort.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/03/28/2f2608d2-cc1e-3fd1-a580-b89478dbd94b.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/67FVFOTaeBUQnimhCWpUkDawDct.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg",
      linkSite: "https://play.max.com/movie/2c394a2d-7d1d-481d-a420-76ee1bee01a7",
      linkVideo: "kmXjPbN-rYU",
      category: "movies",
      favorite: false,
    },
    {
      title: "Harry Potter e as Relíquias da Morte - Parte 2",
      description: "A hora final chegou, o destino apontado na profecia está próximo: o combate mortal entre Harry Potter e Lord Voldemort.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/03/28/da22dfc7-bd2c-3353-90b7-dbfb4af48dbe.png?w=600&f=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/vTbIpnlO0igcGspBsFqBQqaSYzw.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/huEbL4Ow1uhhdf6L3GR6f262Uw4.jpg",
      linkSite: "https://play.max.com/movie/1890c8c5-2f40-4140-a363-064428201826",
      linkVideo: "E79fa8bLfPA",
      category: "movies",
      favorite: true,
    },
    {
        title: "Oppenheimer",
        description: "A história do físico americano J. Robert Oppenheimer, seu papel no Projeto Manhattan e no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, e o quanto isso mudaria a história do mundo para sempre.",
        imageLogo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Oppenheimer_Movie_Logo.svg",
        imagePoster: "https://image.tmdb.org/t/p/original/c0DCmfC7Et2K3URnIJ4ahJpeXR2.jpg",
        imageBanner: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        linkSite: "https://www.primevideo.com/dp/amzn1.dv.gti.1bfde9bc-06c4-472d-84e8-13e019fa34b1?autoplay=0&ref_=atv_cf_strg_wb",
        linkVideo: "F3OxA9Cz17A",
        category: "movies",
        favorite: true,
      },
      {
        title: "Loki",
        description: "O vilão inconstante Loki retoma seu papel como o Deus da Travessura em uma nova série que se passa após os eventos de “Vingadores: Ultimato”.",
        imageLogo: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/147DD4523A44EE8AA6C38B6A7712D0C9CE8C74B3D052073AD8A447B3237D41EB/scale?width=600&aspectRatio=1.78&format=webp",
        imagePoster: "https://image.tmdb.org/t/p/original/voHUmluYmKyleFkTu3lOXQG702u.jpg",
        imageBanner: "https://image.tmdb.org/t/p/original/1pPcHpANG5mGtSYT7MA9QeYOKuK.jpg",
        linkSite: "https://www.disneyplus.com/en-br/series/loki/6pARMvILBGzF?distributionPartner=google",
        linkVideo: "xdBWrkcmMwU",
        category: "series",
        favorite: false,
      },
    {
      title: "Succession",
      description: "A série testa a lealdade de uma família americana rica e magnificamente disfuncional, explorando os negócios internacionais e os perigos do poder no século XXI.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/04/18/1c011b7e-755b-3fec-b605-975cf9346098.png?w=600&f=webp",
      imagePoster: "https://portalpopline.com.br/wp-content/uploads/2023/03/succession-poster-4.jpg",
      imageBanner: "https://images7.alphacoders.com/131/1310210.jpeg",
      linkSite: "https://play.max.com/video/watch/e457df99-f817-4646-b64c-8ce7afaeb405/c18a15b7-73a2-4008-aa8c-1f83f0fffa5c",
      linkVideo: "Gv00b1JjnGc",
      category: "series",
      favorite: true,
    },
    {
      title: "Stranger Things",
      description: "Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que eles encontram são segredos, forças sobrenaturais e uma garota com poderes de outro mundo.",
      imageLogo: "https://occ-0-4907-3852.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABahK2L6Zv0b__1bP4ilacqPDck95q9jyqaSY6LARm54yQ4P6i_mJJB_gx6Wfebu3ScQtyb1iUBXA8w7I8uRuv18puu78eKERbCfh8AL2ogeaKiSAAX9LCuV9YlgdXeEXv6n9TUHXpXaVc6LIyiKONWofkD05nDzBJwZ5qmMWntduhCYvDn8sbw.png?r=23b",
      imagePoster: "https://m.media-amazon.com/images/I/91miBpFYN5L.jpg",
      imageBanner: "https://occ-0-4907-3852.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABer7SeWc6FvkBqWtk61GwL7rshAEVCOARQZVTEJGnLXykYBlO4nbbr6gs7M650BjULuaN6hucXKr5xY2iqPAajrxXd70HawdJeuD.jpg?r=608",
      linkSite: "https://www.netflix.com/br/title/80057281#:~:text=A%20pequena%20cidade%20de%20Hawkins,uma%20menina%20com%20poderes%20sobrenaturais",
      linkVideo: "fLL0_Vy2Wlo",
      category: "series",
      favorite: true,
    },
    {
        title: "The Handmaid's Tale",
        description: "Situado em um futuro distópico, uma mulher é forçada a viver como uma concubina sob uma ditadura teocrática fundamentalista. Uma adaptação para a TV do romance de Margaret Atwood.",
        imageLogo: "https://upload.wikimedia.org/wikipedia/pt/1/1e/The-handmaids-tale-logo.png",
        imagePoster: "https://image.tmdb.org/t/p/original/oIkxqt6ug5zT5ZSUUyc1Iqopf02.jpg",
        imageBanner: "https://image.tmdb.org/t/p/original/sokTOq0zAmPS7wCR4qd4Kca35x7.jpg",
      linkSite: "https://www.paramountplus.com/br/shows/the-handmaids-tale/",
      linkVideo: "TSSyU2uEusQ",
      category: "series",
      favorite: true,
    },
    {
      title: "The Mandalorian",
      description: "A saga de um guerreiro solitário, que também é um mercenário e pistoleiro, viajando pelos territórios esquecidos e marginais do espaço, logo após a queda do Império e antes da criação da temida Primeira Ordem.",
      imageLogo: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6D1FF6E7897E639E425B8794123DB1AC2A04EF8C8CCFE7DE666AC8C2BC27CF0F/scale?width=600&aspectRatio=1.78&format=webp",
      imagePoster: "https://image.tmdb.org/t/p/original/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
      linkSite: "https://www.disneyplus.com/en-br/series/the-mandalorian/3jLIGMDYINqD",
      linkVideo: "BmMbWEj4",
      category: "series",
      favorite: true,
    },
    {
        title: "The Witcher",
      description: "Geralt de Rívia, um caçador de monstros mutante, viaja em direção ao seu destino em um mundo turbulento onde as pessoas às vezes são mais perversas do que os monstros.",
      imageLogo: "https://occ-0-4907-3852.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABecGUSRLB-8TQpC4clEvcX2r3pyFqppuezGOY0yuLYqh82NnMokFY2k-hgxC7r9k4OaMVt6rOZNOTxZPbo2MV0rm448i8EahHTFmaBtfTFTAz6nOZqRJ8GOhpll0qP3ecxJ3_jespkRJd-ETtuAiCAnBtVqgtQx0T63gqbiVVrDdfHce3pb0zg.png?r=21d",
      imagePoster: "https://i.ebayimg.com/images/g/hNwAAOSwsA5kkINc/s-l1200.jpg",
      imageBanner: "https://images5.alphacoders.com/131/1319528.jpeg",
      linkSite: "https://www.netflix.com/br-en/title/80189685?source=35",
      linkVideo: "tjujvMkqWe4",
      category: "series",
      favorite: false,
    },
    {
      title: "A Roda do Tempo",
      description: "Ameaças, novas e muito antigas, perseguem os jovens amigos dos Dois Rios, que agora estão espalhados pelo mundo.",
      imageLogo: "https://m.media-amazon.com/images/S/pv-target-images/f82fba52173cb7ed05435c5d0c523a5e01e8a26535c066417f58a76aa685f264._SX600_FMpng_.png",
      imagePoster: "https://image.tmdb.org/t/p/original/lH1ZRIUQEXvWhY19EjOAGtr9aRc.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/1P3QtW1IkivqDrKbbwuR0zCYIf8.jpg",
      linkSite: "https://www.primevideo.com/dp/amzn1.dv.gti.1c833987-37c3-4dd6-88c1-8510651471d7?autoplay=0&ref_=atv_cf_strg_wb",
      linkVideo: "-u9bPWqIhSg",
      category: "series",
      favorite: true,
    },
    {
      title: "Mãe!",
      description: "Um casal vive em um imenso casarão no campo. Enquanto a jovem esposa passa os dias restaurando o lugar, afetado por um incêndio no passado, o marido mais velho tenta desesperadamente recuperar a inspiração para voltar a escrever os poemas que o tornaram famoso.",
      imageLogo: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Mother%21_movie_horizontal_black_logo.png",
      imagePoster: "https://image.tmdb.org/t/p/original/pqLqxCcFqifgNIFTjDsPVLkfkdu.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/1PZzp9LMfy9hh7q00jSczlKbdDI.jpg",
      linkSite: "https://www.primevideo.com/dp/amzn1.dv.gti.88bc4243-ba9a-adf2-f70b-9db53dbb96d2?autoplay=0&ref_=atv_cf_strg_wb",
      linkVideo: "l8nmbg9NbUI",
      category: "movies",
      favorite: false,
    },
    {
        title: "Percy Jackson e os Olimpianos",
      description: "Percy Jackson é um semideus, filho de Poseidon, o deus dos mares e oceanos na mitologia grega, que precisa aprender a controlar suas habilidades e impedir uma guerra no Olimpo.",
      imageLogo: "https://fiu-original.b-cdn.net/fontsinuse.com/use-images/N180/180824/180824.webp?filename=Pjo.webp",
      imagePoster: "https://pbs.twimg.com/media/GCUc2kja4AAliHc.jpg",
      imageBanner: "https://cdn2.storyasset.link/LAWQx4n1mvh6xbFEYAOH7VlxVAf2/percy-jackson4-npkehcudkx.jpg",
      linkSite: "https://www.disneyplus.com/en-br/series/percy-jackson/ql33aq42HBdr",
      linkVideo: "X7E_8PQER_U",
      category: "series",
      favorite: false,
    },
    {
      title: "Avatar: O Último Mestre do Ar",
      description: "Um garoto conhecido como o Avatar precisa dominar os quatro poderes elementares para salvar um mundo em guerra e enfrentar um inimigo implacável.",
      imageLogo: "https://occ-0-2794-2219.1.nflxso.net/dnm/api/v6/tx1O544a9T7n8Z_G12qaboulQQE/AAAABRwT6zbBuM4KMTamc4Y9R_Ioe-36hTrZHtNHMPBb9VUrvWWKkbzT_a-BN9jAKElt_g4mpE9AHrUTJBVerslFQr_RI5jr1sp6lejO5L7eB-fXpFEMb2OZD-KdywPx5HlkZmwdn7N5ZZ7Y0E0WwpoElMQp0aRZvNqATB-wiH1L_AdQKQV4DgmmpA.png?r=b15",
      imagePoster: "https://cdn.diariodolitoral.com.br/upload/dn_arquivo/2023/11/poster-avatar-o-ultimo-mestre-do-ar.jpg",
      imageBanner: "https://dnm.nflximg.net/api/v6/BvVbc2Wxr2w6QuoANoSpJKEIWjQ/AAAAQWY5K9S1i3yydH_Yxw79TYJ3Q5TPQQJ4JMeB5jdtwbjYcjU6kz6l8CaPxIFIS5JY3m5QIN4aNIF_kvEEJ7VVHecd3DvQqgxaTG7Way-uJjG0DegUwYlVwip4f4DGKUWm3Zw8JImEQzRhAbr9Mc12jGIw4lw.jpg?r=926",
      linkSite: "https://www.netflix.com/br-en/title/80237957?source=35",
      linkVideo: "5llvd1Uu-iU",
      category: "series",
      favorite: false,
    },
    {
      title: "The Walking Dead: The Ones Who Live",
      description: "Rick e Michonne retornam ao universo de The Walking Dead enquanto tentam conciliar osentimento que compartilham com as dificuldades de um mundo tomado pelos zumbis.",
      imageLogo: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ecd51263-bb0f-4465-af86-f7ed25e58e70/def3b3h-00ad57fe-ef89-4f05-a834-551516ad7276.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2VjZDUxMjYzLWJiMGYtNDQ2NS1hZjg2LWY3ZWQyNWU1OGU3MFwvZGVmM2IzaC0wMGFkNTdmZS1lZjg5LTRmMDUtYTgzNC01NTE1MTZhZDcyNzYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.wa68EbBQ8_rOT74Hr4aJVACxQDujiw4YhtOfn1HB_wE",
      imagePoster: "https://www.liveforfilm.com/wp-content/uploads/2024/01/the-walking-dead-the-ones-who-live-poster.jpg",
      imageBanner: "https://images8.alphacoders.com/135/thumb-1920-1353207.jpeg",
      linkSite: "https://www.amc.com/shows/the-walking-dead-the-ones-who-live--1060743",
      linkVideo: "gKcKby8xrCI",
      category: "series",
      favorite: false,
    },
    {
      title: "Adão Negro",
      description:
        "O poderoso Adão Negro é libertado de sua tumba para lançar sua justiça cruel sobre a Terra.",
      imageLogo: "https://images.cdn.prd.api.discomax.com/2023/02/13/d57c4470-7ffb-314f-a041-29eca31763e0.png?w=600&f=webp",
      imagePoster:
        "https://ultimato.com.br/image/atualiza_home/principal/ultimas/opiniao/2022/10_out/opi_1-11-22_carlos_caldas_adao_negro.jpg",
      imageBanner: "https://image.tmdb.org/t/p/original/qBx97wytqlyPqXATHqRgIVFxJRU.jpg",
      linkSite: "https://play.max.com/movie/0c730836-253b-4338-a3d1-a6a44a3384e0",
      linkVideo: "HluMG9tJXHM",
      category: "movies",
      favorite: false,
    },
    {
      title: "Jurassic World: Domínio",
      description:
        "Quatro anos após a destruição da Ilha Nublar, os dinossauros agora vivem e caçam ao lado de humanos em todo o mundo. Esse frágil equilíbrio remodela o futuro e deve determinar de uma vez por todas se os seres humanos continuarão sendo a espécie dominante em um planeta que agora compartilham com as criaturas mais temíveis da história",
        imageLogo: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4c0a86db-d334-4bff-b302-5a1a26f708a3/de1nwqr-b9ae17af-0386-4fb0-b7e7-2c446087e241.png/v1/fill/w_810,h_688/jurassic_world_dominion_logo_png_by_kevindaghost_de1nwqr-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9Njg4IiwicGF0aCI6IlwvZlwvNGMwYTg2ZGItZDMzNC00YmZmLWIzMDItNWExYTI2ZjcwOGEzXC9kZTFud3FyLWI5YWUxN2FmLTAzODYtNGZiMC1iN2U3LTJjNDQ2MDg3ZTI0MS5wbmciLCJ3aWR0aCI6Ijw9ODEwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.aVT18Ooaxpr8YWl9O9EadUnN0_ZIec8oII4LRwPNNls",
      imagePoster:
        "https://oregional.com.br/media/blog/700ba1039467a09248591758e0f51869.jpg",
      imageBanner: "https://images6.alphacoders.com/123/1239922.jpg",
      linkSite: "https://www.primevideo.com/dp/amzn1.dv.gti.60df7de6-7ed6-4e3b-ad43-b13aeac3367c?autoplay=0&ref_=atv_cf_strg_wb",
      linkVideo: "hcv_8WXSetM",
      category: "movies",
      favorite: false,
    },
    {
      title: "Vingadores: Ultimato",
      description:
        "Após Thanos eliminar metade das criaturas vivas, os Vingadores têm de lidar com a perda de amigos e entes queridos. Com Tony Stark vagando perdido no espaço sem água e comida, Steve Rogers e Natasha Romanov lideram a resistência contra o titã louco.",
        imageLogo: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/AE060EFCFDBE2729E3CD8AC7D83536FB32FDD1CB7862FAC7FF71BC2184884E67/scale?width=1440&aspectRatio=1.78&format=png",
      imagePoster:
        "https://upload.wikimedia.org/wikipedia/pt/thumb/9/9b/Avengers_Endgame.jpg/250px-Avengers_Endgame.jpg",
      imageBanner: "https://images8.alphacoders.com/100/thumb-1920-1003220.png",
      linkSite: "https://www.disneyplus.com/movies/marvel-studios-avengers-endgame/aRbVJUb2h2Rf",
      linkVideo: "g6ng8iy-l0U",
      category: "movies",
      favorite: false,
    },
  ],
  categories: [
    { name: "Filmes", type: "movies" },
    { name: "Séries", type: "series" },
  ],
};